version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        versions: ["21"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      emotion:
        patterns:
          - "@emotion/*"
      fortawesome:
        patterns:
          - "@fortawesome/*"
      mui:
        patterns:
          - "@mui/*"
      next:
        patterns:
          - "eslint-config-next"
          - "next"
          - "@next/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
