version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "node"
        versions: ["27"]
    groups:
      monthly-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      monthly-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      monthly-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      monthly-major:
        patterns:
          - "*"
        update-types:
          - "major"
