rules:
  linebreak-style:
    - 2
    - unix
  # Following rules override eslint-config-airbnb
  quotes:
    - 2
    - double
  comma-dangle:
    - 0
  # Following rules may be changed in the future
  max-len:
    - 0
  no-param-reassign:
    - 0
  no-underscore-dangle:
    - 0
env:
  browser: true
  es6: true
plugins:
  - react
settings:
  import/resolver: webpack
parser: babel-eslint
extends:
  - "airbnb"
