rules:
  indent:
    - 2
    - 2
  quotes:
    - 2
    - double
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  no-console:
    - 1
env:
  browser: true
  es6: true
  node: true
parser: babel-eslint
plugins:
  - react
parserOptions:
  ecmaFeatures:
    jsx: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"