rules:
  linebreak-style:
    - error
    - unix
  # Following rules override eslint-config-airbnb
  quotes:
    - error
    - double
  # Following rules may be changed in the future
  import/extensions:  # Bug??
    - off
  react/jsx-filename-extension:
    - off
  react/jsx-no-target-blank:
    - warn
  max-len:
    - off
  no-underscore-dangle:
    - off
  jsx-a11y/anchor-has-content:
    - off
env:
  browser: true
  es6: true
globals:
  # See webpack.DefinePlugin settings in the webpack configuration
  __DEBUG__: true
  __PRODUCTION__: true
  __CLIENT__: true
  __SERVER__: true
plugins:
  - react
settings:
  import/resolver: webpack
parser: babel-eslint
extends:
  - "airbnb"
