extends:
  - airbnb
  - "plugin:@typescript-eslint/recommended"
  # https://nextjs.org/docs/basic-features/eslint#additional-configurations
  - "next/core-web-vitals"
rules:
  linebreak-style:
    - error
    - unix
  "@typescript-eslint/indent":
    - error
    - 2
  # Following rules override eslint-config-airbnb
  quotes:
    - error
    - double
  # Following rules may be changed in the future
  import/extensions:
    - off
  import/no-unresolved:
    - off
  react/jsx-filename-extension:
    - off
  react/jsx-props-no-spreading:
    - off
  react/state-in-constructor:
    - error
    - never
  "@typescript-eslint/ban-ts-comment":
    - warn
  "@typescript-eslint/explicit-function-return-type":
    - off
  "@typescript-eslint/explicit-member-accessibility":
    - off
  # Fix for https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-use-before-define.md#how-to-use
  no-use-before-define:
    - off
  "@typescript-eslint/no-use-before-define":
    - error
