// flow-typed signature: 3a124e8fb3f61ff8e9e7a761c0e61b80
// flow-typed version: <<STUB>>/smoothscroll_v^0.4.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smoothscroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'smoothscroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smoothscroll/smoothscroll' {
  declare module.exports: any;
}

declare module 'smoothscroll/smoothscroll.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smoothscroll/smoothscroll.js' {
  declare module.exports: $Exports<'smoothscroll/smoothscroll'>;
}
declare module 'smoothscroll/smoothscroll.min.js' {
  declare module.exports: $Exports<'smoothscroll/smoothscroll.min'>;
}
