// flow-typed signature: a5a3076c5ef41646e1b6db8270c46bd5
// flow-typed version: <<STUB>>/styled-jsx_v^3.1.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-jsx/babel-test' {
  declare module.exports: any;
}

declare module 'styled-jsx/babel' {
  declare module.exports: any;
}

declare module 'styled-jsx/css' {
  declare module.exports: any;
}

declare module 'styled-jsx/dist/_constants' {
  declare module.exports: any;
}

declare module 'styled-jsx/dist/_utils' {
  declare module.exports: any;
}

declare module 'styled-jsx/dist/babel-external' {
  declare module.exports: any;
}

declare module 'styled-jsx/dist/babel-test' {
  declare module.exports: any;
}

declare module 'styled-jsx/dist/babel' {
  declare module.exports: any;
}

declare module 'styled-jsx/dist/lib/style-transform' {
  declare module.exports: any;
}

declare module 'styled-jsx/dist/lib/stylesheet' {
  declare module.exports: any;
}

declare module 'styled-jsx/dist/macro' {
  declare module.exports: any;
}

declare module 'styled-jsx/dist/server' {
  declare module.exports: any;
}

declare module 'styled-jsx/dist/style' {
  declare module.exports: any;
}

declare module 'styled-jsx/dist/stylesheet-registry' {
  declare module.exports: any;
}

declare module 'styled-jsx/dist/webpack' {
  declare module.exports: any;
}

declare module 'styled-jsx/lib/style-transform' {
  declare module.exports: any;
}

declare module 'styled-jsx/lib/stylesheet' {
  declare module.exports: any;
}

declare module 'styled-jsx/macro' {
  declare module.exports: any;
}

declare module 'styled-jsx/server' {
  declare module.exports: any;
}

declare module 'styled-jsx/style' {
  declare module.exports: any;
}

declare module 'styled-jsx/webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-jsx/babel-test.js' {
  declare module.exports: $Exports<'styled-jsx/babel-test'>;
}
declare module 'styled-jsx/babel.js' {
  declare module.exports: $Exports<'styled-jsx/babel'>;
}
declare module 'styled-jsx/css.js' {
  declare module.exports: $Exports<'styled-jsx/css'>;
}
declare module 'styled-jsx/dist/_constants.js' {
  declare module.exports: $Exports<'styled-jsx/dist/_constants'>;
}
declare module 'styled-jsx/dist/_utils.js' {
  declare module.exports: $Exports<'styled-jsx/dist/_utils'>;
}
declare module 'styled-jsx/dist/babel-external.js' {
  declare module.exports: $Exports<'styled-jsx/dist/babel-external'>;
}
declare module 'styled-jsx/dist/babel-test.js' {
  declare module.exports: $Exports<'styled-jsx/dist/babel-test'>;
}
declare module 'styled-jsx/dist/babel.js' {
  declare module.exports: $Exports<'styled-jsx/dist/babel'>;
}
declare module 'styled-jsx/dist/lib/style-transform.js' {
  declare module.exports: $Exports<'styled-jsx/dist/lib/style-transform'>;
}
declare module 'styled-jsx/dist/lib/stylesheet.js' {
  declare module.exports: $Exports<'styled-jsx/dist/lib/stylesheet'>;
}
declare module 'styled-jsx/dist/macro.js' {
  declare module.exports: $Exports<'styled-jsx/dist/macro'>;
}
declare module 'styled-jsx/dist/server.js' {
  declare module.exports: $Exports<'styled-jsx/dist/server'>;
}
declare module 'styled-jsx/dist/style.js' {
  declare module.exports: $Exports<'styled-jsx/dist/style'>;
}
declare module 'styled-jsx/dist/stylesheet-registry.js' {
  declare module.exports: $Exports<'styled-jsx/dist/stylesheet-registry'>;
}
declare module 'styled-jsx/dist/webpack.js' {
  declare module.exports: $Exports<'styled-jsx/dist/webpack'>;
}
declare module 'styled-jsx/lib/style-transform.js' {
  declare module.exports: $Exports<'styled-jsx/lib/style-transform'>;
}
declare module 'styled-jsx/lib/stylesheet.js' {
  declare module.exports: $Exports<'styled-jsx/lib/stylesheet'>;
}
declare module 'styled-jsx/macro.js' {
  declare module.exports: $Exports<'styled-jsx/macro'>;
}
declare module 'styled-jsx/server.js' {
  declare module.exports: $Exports<'styled-jsx/server'>;
}
declare module 'styled-jsx/style.js' {
  declare module.exports: $Exports<'styled-jsx/style'>;
}
declare module 'styled-jsx/webpack.js' {
  declare module.exports: $Exports<'styled-jsx/webpack'>;
}
