version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.20

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build
      - run: npm run export
      - run: npm test

  build-and-push-docker-image:
    docker:
      - image: docker:git

    steps:
      - checkout
      - setup_remote_docker
      - run: docker run --rm -i hadolint/hadolint < Dockerfile
      - run: docker build -t portfolio .
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
              docker tag portfolio "ymyzk/portfolio:$CIRCLE_SHA1"
              docker push "ymyzk/portfolio:$CIRCLE_SHA1"
              docker tag portfolio "ymyzk/portfolio:latest"
              docker push "ymyzk/portfolio:latest"
            fi

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - build-and-push-docker-image:
          requires:
            - build
