name: Build

on: [push]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm test
      - if: ${{ matrix.node-version == '20.x' }}
        uses: actions/upload-artifact@v3
        with:
          name: portfolio
          path: out

  test-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run hadolint
        run: docker run --rm -i hadolint/hadolint:latest < Dockerfile

  build-docker-images:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - build-app
      - test-dockerfile
    steps:
      - uses: actions/checkout@v4
      - run: docker version
      - run: docker build -t portfolio .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Container Registry
        run: |
          docker tag portfolio ghcr.io/ymyzk/portfolio:$GITHUB_SHA
          docker tag portfolio ghcr.io/ymyzk/portfolio:latest
          docker push ghcr.io/ymyzk/portfolio:$GITHUB_SHA
          docker push ghcr.io/ymyzk/portfolio:latest

  upload-to-cf-pages:
    runs-on: ubuntu-latest
    needs:
      - build-app
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: portfolio
          path: out
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ymyzk-portfolio
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
