name: Build

on: [push]

jobs:
  build-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm run export
      - run: npm test

  test-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run hadolint
        run: docker run --rm -i hadolint/hadolint:latest < Dockerfile

  build-docker-images:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - build-app
      - test-dockerfile
    steps:
      - uses: actions/checkout@v2
      - run: docker version
      - run: docker build -t portfolio .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push to Docker Hub
        run: |
          docker tag portfolio ymyzk/portfolio:latest
          docker push ymyzk/portfolio:latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Container Registry
        run: |
          docker tag portfolio ghcr.io/ymyzk/portfolio:latest
          docker push ghcr.io/ymyzk/portfolio:latest
